names = {
    # BRASIL
    "Athletico-PR": ["Athletico Paranaense"],
    "Atlético-GO": ["Atlético GO", "Atlético Goianiense"],
    "Atlético-MG": ["Atlético Mineiro", "Atletico Mineiro", "Atlético MG"],
    "Bahia": ["Bahia BA"],
    "Botafogo": ["Botafogo-RJ", "Botafogo FR RJ"],
    "Corinthians": [],
    "Criciúma": ["Criciuma"],
    "Cruzeiro": [],
    "Cuiabá": ["Cuiaba", "Cuiabá EC"],
    "Flamengo": [],
    "Fluminense": [],
    "Fortaleza": [],
    "Grêmio": ["Gremio"],
    "Internacional": [],
    "Juventude": [],
    "Palmeiras": [],
    "Bragantino": ["RB Bragantino"],
    "São Paulo": ["Sao Paulo"],
    "Vasco": ["Vasco da Gama"],
    "Vitória": ["Vitoria BA"],
    "Amazonas AM": ["Amazonas"],
    "Santos": [],
    "América-MG": ["América FC", "América Mineiro"],
    "Vila Nova": [],
    "Avaí": [],
    "Coritiba": ["Coritiba PR"],
    "Botafogo-SP": ["Botafogo de Ribeirão Preto"],
    "Mirassol": [],
    "CRB": [],
    "Chapecoense": [],
    "Goiás": [],
    "Ituano": [],
    "Grêmio Novorizontino": ["Novorizontino"],
    "Ceará": [],
    "Guarani-SP": ["Guarani"],
    "Operário-PR": ["Operário PR"],
    "Ponte Preta": [],
    "Sport Recife": ["Sport"],
    "Brusque SC": ["Brusque"],

    # ENGLAND
    "Aston Villa": ["Aston Villa"],
    "Liverpool": [],
    "Bournemouth": ["AFC Bournemouth", "Bournemouth"],
    "Brentford": [],
    "Everton": ["Everton", "Everton FC"],
    "Sheffield United": ["Sheffield United", "Sheff Utd"],
    "Fulham": ["Fulham", "Fulham FC"],
    "Manchester City": ["Man. City", "Man City", "Manchester City"],
    "Manchester United": ["Man United", "Man Utd", "Manchester United"],
    "Arsenal": [],
    "Newcastle United": ["Newcastle", "Newcastle United"],
    "Brighton & Hove Albion": ["Brighton", "Brighton & Hove Albion"],
    "Nottingham Forest": ["Nottingham Forest", "Nottm Forest"],
    "Chelsea": [],
    "Tottenham Hotspur": ["Tottenham", "Tottenham Hotspur"],
    "Burnley": [],
    "West Ham United": ["West Ham", "West Ham United"],
    "Luton Town": ["Luton", "Luton Town"],
    "Wolverhampton Wanderers": ["Wolves", "Wolverhampton", "Wolverhampton Wanderers"],
    "Crystal Palace": [],

    # SPAIN
    "Athletic Bilbao": ["Athletic Bilbao"],
    "Osasuna": [],
    "Atlético de Madrid": ["Atlético Madrid", "Atlético de Madrid", "Atletico de Madrid"],
    "Celta de Vigo": ["Celta de Vigo"],
    "Barcelona": [],
    "Real Sociedad": [],
    "Real Betis": ["Bétis", "Real Bétis", "Betis"],
    "UD Almería": ["Almería", "UD Almeria"],
    "Cádiz CF": ["Cadiz", "Cádiz CF", "Cadiz CF"],
    "Getafe CF": ["Getafe", "Getafe CF"],
    "Deportivo Alavés": ["Alavés", "CD Alavés", "Deportivo Alaves", "CD Alaves"],
    "Girona FC": ["Girona", "Girona FC"],
    "Granada": [],
    "Real Madrid": [],
    "Mallorca": ["Maiorca", "Mallorca"],
    "UD Las Palmas": ["Las Palmas", "UD Las Palmas"],
    "Valencia": ["Valência", "Valencia"],
    "Rayo Vallecano": ["Rayo", "Rayo Vallecano"],
    "Villarreal CF": ["Villarreal", "Villarreal CF"],
    "Sevilla FC": ["Sevilha FC", "Sevilla FC", "Sevilla", "Sevilha"],

    # GERMANY
    "1. FC Köln": ["Köln", "Colônia"],
    "1. FC Union Berlin": ["Union Berlin"],
    "FC Augsburg": ["Augsburg"],
    "VfB Stuttgart": ["Stuttgart", "VfB Estugarda"],
    "Bayern Munich": ["Bayern Munique", "Bayern München", "Bayern"],
    "VfL Wolfsburg": ["Wolfsburg"],
    "Borussia Mönchengladbach": ["Borussia Monchengladbach", "Borussia M'gladbach"],
    "Eintracht Frankfurt": [],
    "SC Freiburg": ["Freiburg"],
    "1. FC Heidenheim": ["Heidenheim", "FC Heidenheim"],
    "FSV Mainz 05": ["Mainz 05", "Mainz", "1. FSV Mainz 05"],
    "Borussia Dortmund": [],
    "RB Leipzig": [],
    "Werder Bremen": [],
    "SV Darmstadt 98": ["Darmstadt"],
    "TSG 1899 Hoffenheim": ["Hoffenheim", "TSG Hoffenheim"],
    "VfL Bochum": ["Bochum"],
    "Bayer Leverkusen": [],

    # ITALY
    "AC Milan": ["Milan"],
    "Atalanta": [],
    "Fiorentina": [],
    "Frosinone": [],
    "Inter Milan": ["Inter de Milão", "Inter"],
    "Genoa": ["Genoa CFC"],
    "Hellas Verona": ["Verona"],
    "Juventus": ["Juventus FC"],
    "Lazio": [],
    "Lecce": ["US Lecce"],
    "Napoli": [],
    "Bologna": ["Bologna FC", "Bolonha"],
    "Roma": [],
    "Cagliari": [],
    "Torino": [],
    "Salernitana": [],
    "Empoli": [],
    "Monza": ["AC Monza"],
    "Sassuolo": [],
    "Udinese": [],

    # FRANCE
    "Brest": ["Brestois"],
    "Stade de Reims": ["Reims"],
    "Clermont": ["Clermont Foot"],
    "Lyon": [],
    "Strasbourg": ["Estrasburgo"],
    "FC Metz": ["Metz"],
    "Montpellier": [],
    "Monaco": ["Mônaco"],
    "Nantes": [],
    "Lille": [],
    "Nice": [],
    "Le Havre": ["Le Havre AC"],
    "Olympique de Marseille": ["Marseille", "Marselha"],
    "FC Lorient": ["Lorient"],
    "Paris Saint-Germain": ["PSG"],
    "Toulouse": ["Toulouse FC"],
    "Rennes": ["Stade Rennais"],
    "Lens": [],

    # USA
    "Atlanta United FC": ["Atlanta United"],
    "CF Montreal": ["CF Montréal"],
    "Charlotte FC": ["Charlotte"],
    "Columbus Crew SC": ["Columbus Crew"],
    "D.C. United": ["DC United"],
    "FC Cincinnati": [],
    "FC Dallas": [],
    "Houston Dynamo FC": ["Houston Dynamo"],
    "Inter Miami CF": [],
    "LA Galaxy": [],
    "Los Angeles FC": [],
    "Minnesota United FC": ["Minnesota United"],
    "Nashville SC": [],
    "New England Revolution": [],
    "New York City FC": [],
    "New York Red Bulls": [],
    "Orlando City SC": ["Orlando City"],
    "Philadelphia Union": [],
    "Portland Timbers": [],
    "Real Salt Lake": [],
    "San Jose Earthquakes": [],
    "Seattle Sounders FC": ["Seattle Sounders"],
    "Sporting Kansas City": [],
    "Toronto FC": [],
    "Vancouver Whitecaps FC": ["Vancouver Whitecaps"],
    "Chicago Fire FC": ["Chicago Fire"],
    "St. Louis City SC": ["St. Louis City"],

    # DENMARK
    "Brøndby": ["Brondby", "Brondby IF"],
    "FC Copenhagen": ["Copenhagen", "FC Copenhagen"],
    "FC Nordsjælland": ["FC Nordsjaelland", "Nordsjaelland"],
    "Silkeborg": ["Silkeborg", "Silkeborg IF"],
    "Midtjylland": ["Midtjylland", "FC Midtjylland"],
    "AGF Aarhus": ["AGF Aarhus", "Aarhus GF"],
    "Odense BK": ["Odense BK"],
    "Lyngby": ["Lyngby BK", "Lyngby"],
    "Randers FC": ["Randers FC"],
    "Hvidovre IF": ["Hvidovre IF"],
    "Viborg": ["Viborg", "Viborg FF"],
    "Vejle BK": ["Vejle BK", "Vejle", "Vejle Boldklub"],
}

def rename(name):
    for key, values in names.items():
        if name in values:
            return key
    return name